### ISSUE TITLE
modifications to Wifi.cpp

### ISSUE THREAD

**Issue by squonk11** [PerMalmberg/Smooth#113]
Hello,
I found a bug in Wifi.cpp which results from my implementation of the softap mode: the function `get_mac_address()` always returns the MAC address of the station interface only. But in case softap mode it must return the MAC address of the ap-interface (which actually is different from the MAC address of the station interface).
Shall I fix this and send a PR?
If yes: for my application I would need to get the MAC address and the IP address in binary format (e.g.`uint8_t ip[4]` and `uint8_t mac[6]`) from the Wifi class. Can I implement this also in the same PR?

**Comment by PerMalmberg** [comment]
Please, go ahead.

**Comment by PerMalmberg** [comment]
I'll close this as #114 in progress.
