### ISSUE TITLE
Rename DisplaySpi to something else

### ISSUE THREAD

**Issue by PerMalmberg** [PerMalmberg/Smooth#130]
`DisplaySpi` is a too generic name. Although it is currently used for three different LCD drivers (IL9341, SH1107 and ST7735) the implementation does not match up with a driver for a WaveShare device which also uses the SPI bus.

@enelson1001 Dou you have a suggestion on a name that reflects the family of devices that the `DisplaySpi` targets?

**Comment by enelson1001** [comment]
Maybe LcdSpi, since all three displays are lcd displays.  Similar to what is written in this article 
https://www.r-tt.com/technology-articles/eink-vs-lcd.html

Another option is ActiveSpi (for LCD displays) and StaticSpi (for E-Paper displays) but I don't like as much.

**Comment by PerMalmberg** [comment]
Ok, I'll go with simply `LCD` since "display" is part of the acronym and no need to put the bus type in the class name imho. Thanks for your input.

**Comment by enelson1001** [comment]
There are some i2c displays also - typically monochrome

**Comment by PerMalmberg** [comment]
Yeah, that's true. LCDSpi it is then.
