### ISSUE TITLE
SystemStatistics.h needs #pragma once

### ISSUE THREAD

**Issue by Paul-Simpson** [PerMalmberg/Smooth#147]
..otherwise compilation errors out with:

In file included from ../components/motor/include/motor.h:7,
                 from ../main/main.h:10,
                 from ../main/main.cpp:8:
../externals/smooth/lib/smooth/include/smooth/core/SystemStatistics.h:55:11: error: redefinition of 'class smooth::core::SystemStatistics'
     class SystemStatistics

Adding the pragma fixes the issue.

PS - thank you for sharing this framework. It's early days for me, but I'm loving it. :)

**Comment by PerMalmberg** [comment]
> PS - thank you for sharing this framework. It's early days for me, but I'm loving it. :)

Glad it can be of help.

Please open a PR with the requested change and I'll merge it to master.

**Comment by Paul-Simpson** [comment]
Done.

**Comment by PerMalmberg** [comment]
Merged.
