### ISSUE TITLE
github actions: compile host and esp32 build in parallel

### ISSUE THREAD

**Issue by peterus** [PerMalmberg/Smooth#152]
I suggest to compile the host- and esp32-build in parallel to reduce runtime.

the `CI`-job (https://github.com/PerMalmberg/Smooth/blob/master/.github/workflows/ci.yml) should be splitted up in `CI-host` and `CI-esp32` jobs. the corresponding scripts should be started in the different jobs.
This split will reduce the runtime dramatically (would expect the runtime will be just the half).

If this change is okay for you, I am happy to do the changes.

**Comment by PerMalmberg** [comment]
Absolutely. please do. If possible, I'd like to see a script that runs both, for use locally.

**Comment by peterus** [comment]
Branch merged - closing Ticket
