### ISSUE TITLE
Change Task tick up once it's created

### ISSUE THREAD

**Issue by Paul-Simpson** [PerMalmberg/Smooth#154]
Hi,

Apologies if this is a silly question, but is there a way to change the tick duration of an already running task? If not, I'll look into implementing - but want to ask beforehand.

P

**Comment by PerMalmberg** [comment]
No, there's not. It's meant to be fixed. I don't know your exact use-case, but I recommend using a timer instead, those you can [start/stop and set the interval as you desire](https://github.com/PerMalmberg/Smooth/blob/master/lib/smooth/include/smooth/core/timer/Timer.h#L101).

**Comment by Paul-Simpson** [comment]
Thank you!
