### ISSUE TITLE
[Feature Request] PPPoS support

### ISSUE THREAD

**Issue by mapedraza** [PerMalmberg/Smooth#169]
It would be great to have [PPPoS support](https://github.com/espressif/esp-idf/tree/release/v3.3/examples/protocols/pppos_client) for having the possibility of sending and receiving data through an external modem (like SIM800). There are several boards in the market that integrates a modem together with the ESP32 module like [LyliGo T-CALL](https://github.com/Xinyuan-LilyGO/LilyGo-T-Call-SIM800)

Thanks in advance

**Comment by PerMalmberg** [comment]
> It would be great to have [PPPoS support](https://github.com/espressif/esp-idf/tree/release/v3.3/examples/protocols/pppos_client) for having the possibility of sending and receiving data through an external modem (like SIM800). There are several boards in the market that integrates a modem together with the ESP32 module like [LyliGo T-CALL](https://github.com/Xinyuan-LilyGO/LilyGo-T-Call-SIM800)
> 
> Thanks in advance

That could be useful to have.

As there is no actual question in the above statement I'm going to close this issue.
