### ISSUE TITLE
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled. Core 1 register dump:

### ISSUE THREAD

**Issue by luuvt** [PerMalmberg/Smooth#2]
Hello Smooth.
i'm using framework Smooth for esp32
getting below error and my esp32 gets rebooting ,
please suggest how to fix it,
**Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x4008c484  PS      : 0x00060733  A0      : 0x8008c522  A1      : 0x3ffc2bb0
0x4008c484: prvCheckTasksWaitingTermination at /home/luutran/kante/esp/esp-idf/components/freertos/tasks.c:4740

A2      : 0x00000005  A3      : 0x00000001  A4      : 0x00000000  A5      : 0x3ffc24ec
A6      : 0x00000000  A7      : 0x00000001  A8      : 0x8008c46e  A9      : 0x3ffc2b90
A10     : 0x3ffc0b44  A11     : 0x00000000  A12     : 0x007d317b  A13     : 0x00000001
A14     : 0x00060021  A15     : 0x00000000  SAR     : 0x00000000  EXCCAUSE: 0x0000001c
EXCVADDR: 0x0000004d  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000

Backtrace: 0x4008c484:0x3ffc2bb0 0x4008c51f:0x3ffc2bd0
0x4008c484: prvCheckTasksWaitingTermination at /home/luutran/kante/esp/esp-idf/components/freertos/tasks.c:4740

0x4008c51f: prvIdleTask at /home/luutran/kante/esp/esp-idf/components/freertos/tasks.c:4740

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:5736
load:0x40078000,len:7684
load:0x40080000,len:7384

**Comment by PerMalmberg** [comment]
My suggestion: Debug your code. Nothing points to this being a problem in the Smooth framework.
