### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by enelson1001** [PerMalmberg/Smooth#6]
Per
This is not an issue with the Smooth library just a feature request.  
Could you add RMT to your io's and maybe some event handling.  Hopefully this is something you been thinking about doing.  
Right now I have written code using Task from esp32-snippets and think it could be vastly improved with your library.  I am using both RMT transmitter and an RMT receiver.  
In Project Simulator I use the the RMT transmitter to simulates the transmission of a message from product XYZ.  I have the RMT transmitter in a Task waiting for me to feed it std::vector<rmt_item32_t> data to send out.  The simulator has a class that builds a raw message from data provided to it and another class that converts the raw message to and RMT message.  This class then passes the RMT data to the RMT transmitter.  The message sent out includes sync bits + message  + end of message bit.  I have this project working.
In Project App I use the RMT receiver in a Task that is constantly sending chucks of RMT messages received to another Task that is converting RMT bits to raw bits (sync, data, end of message) and looking for a signature that indicates that a real message has been received. In the real world the RMT receiver is constantly receiving a stream of bits (most of the time its junk).  The raw byte message received is then passed to another Task to parse the message and get the data from it.  I am still working on this project.

1. Do you foresee adding RMT in the near future (ie 2-3 months).
2. If you are not adding RMT in the near future what pieces of your existing code would you recommend I look at to create an RMT io.  
3. Or is it possible to use what you current have and just add xxx to provide RMT.
4. Have you thought about a uart io.  Has similar properties: transmitter and receiver.

Thanks

**Comment by PerMalmberg** [comment]
The RMT interface is pretty clean as-is so I've seen no reason create a "RMT IO" class. I've only used RMT to control [RGB leds](https://github.com/PerMalmberg/Smooth/blob/master/lib/smooth/application/rgb_led/RGBLed.cpp). You might be able to use ideas for that as a base for an output device.

I've not had a reason to look at serial communication using UARTs.

May I ask what product you're developing?
