### ISSUE TITLE
build system

### ISSUE THREAD

**Issue by squonk11** [PerMalmberg/Smooth#84]
I was trying to switch from my "hand crafted" build system to the one you suggest in README.md. I am working under windows 10. If I follow your instructions I encounter the following problems:

1. when running the command `cmake .. -G "Ninja" -DESP_PLATFORM=1 -DCMAKE_TOOLCHAIN_FILE=$IDF_PATH/tools/cmake/toolchain-esp32.cmake && ninja` I get error messages because (for whatever reasons) cmake gets confused by a MS Visual C++ compiler which is also installed on my PC. In order to avoid this I must use the command suggested by the epressif build system `idf.py build`

2. But when I use `idf.py build` or `idf.py menuconfig` I get error messages due to the use of wrong slashes in paths (windows style "\" instead of cmake style "/"). In order to avoid this I have to modify in .\CMakeLists.txt the line `set(EXTRA_COMPONENT_DIRS externals/smooth/smooth_component)` to `set(EXTRA_COMPONENT_DIRS ${idf_path}/externals/smooth/smooth_component)`. And I have to modify in .\main\CMakeLists.txt the line `$ENV{IDF_PATH}/components` to `${idf_path}/components`.

3. After the above modifications I get the error message that `externals\nlohman_json` is missing (because it is not installed). In order to avoid this I need to update all submodules of esp-idf using `git submodule update --init --recursive`.

4. After the steps 1 - 3 I am able to run menuconfig but when compiling I get an error message during linking that `app_main` is missing. In order to avoid this I have to put the following code into my main.cpp:     
    extern "C"
    {
    #ifdef ESP_PLATFORM
    void app_main()
    {
        App app{};
        app.start();
    }
    #else
    int main(int /*argc*/, char** /*argv*/)
    {
        smooth::core::SystemStatistics::instance().dump();
        App app{};
        app.start();
        return 0;
    }
    #endif

    } 

With the modifications 1 - 4 I am able to compile a sample project. Do you think it could make sense to add some instructions to README.md in order to make it easier for windows users to get started with Smooth?

**Comment by PerMalmberg** [comment]
1. Confused how? I don't know what `idf.py build` does differently, but running CMake to generate the build system from CMake files is the standard way. If you have local issues, then my guess it is a problem with wrong binaries being used du to being placed on the path...

2. If you have to use `set(EXTRA_COMPONENT_DIRS ${idf_path}/externals/smooth/smooth_component)` it means you have placed Smooth under `${idf_path}, not under your project as per the instructions. I can see why you got it wrong as it says

    In your ESP-IDF projects's root

What was meant is this

    In your project's root (which uses ESP-IDF)

I'll update the readme to the second version.

3. This is already going into from this PR: #82 

4. Yeah, that info is [available here](https://github.com/PerMalmberg/Smooth/blob/master/test/test.cpp.in) but it is not easily found. Adding that would be a good idea.

**Comment by squonk11** [comment]
1. `my guess it is a problem with wrong binaries being used du to being placed on the path`; probably that is the case here.

2. o.k. this I misunderstood

3. o.k.

4. this was not too difficult to figure out. But a hint could be helpful.

**Comment by PerMalmberg** [comment]
Master updated with an example at the bottom.
