### ISSUE TITLE
Build fails - externals/smooth/externals/nlohman_json/include' is not a directory.

### ISSUE THREAD

**Issue by enelson1001** [PerMalmberg/Smooth#94]
I executed the following script as stated on readme page.
git submodule add https://github.com/PerMalmberg/Smooth.git externals/smooth
But there are no files in nlohman_json folder.
Is there an additional script needed to download the nlohman_jason files?

**Comment by PerMalmberg** [comment]
Update submodules: `git submodule update --init --checkout --recursive`
