### ISSUE TITLE
Recommended version of ESP-IDF for Smooth

### ISSUE THREAD

**Issue by enelson1001** [PerMalmberg/Smooth#96]
Which version do you recommend using with Smooth.
1. release-v4.0
2. v4.0-beta1

**Comment by PerMalmberg** [comment]
Personally, I've always used master and that's what I test against. I don't know the difference between the two you named.

**Comment by enelson1001** [comment]
I tried v4.0-beta1 but had compiling errors with wpa supplicant. Been using
release/v4.0 without any problems (so far).

**Comment by PerMalmberg** [comment]
Compile errors due to Smooth?

**Comment by enelson1001** [comment]
No, esp-idf/components.  lot of undefined references.
